In [1]:
import torch
from torch.nn import functional as F

In [2]:
bj = 0
bjp1 = 1
beta = 0.1
d = 4

idx = torch.arange(d)
boundary_mask = F.sigmoid((idx - bj) / beta) * F.sigmoid((bjp1 - idx) / beta)

In [3]:
boundary_mask

tensor([4.9998e-01, 4.9998e-01, 4.5398e-05, 2.0612e-09])

In [12]:
idx - bj

tensor([0, 1, 2, 3])

In [11]:
bjp1 - idx

tensor([ 1,  0, -1, -2])

In [10]:
F.sigmoid(idx - bj) * F.sigmoid(bjp1 - idx)

tensor([0.3655, 0.3655, 0.2369, 0.1135])